# Generated by Django 5.0 on 2024-01-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.category')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.word')),
            ],
            options={
                'unique_together': {('word', 'category')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='categories',
            field=models.ManyToManyField(through='randomizer.WordCategory', to='randomizer.category'),
        ),
    ]
