# Generated by Django 5.0.1 on 2024-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='categories',
            field=models.ManyToManyField(related_name='words', through='randomizer.WordCategory', to='randomizer.category'),
        ),
    ]
