# Generated by Django 5.0.1 on 2024-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0002_alter_word_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='categories',
            field=models.ManyToManyField(through='randomizer.WordCategory', to='randomizer.category'),
        ),
    ]
