# Generated by Django 5.0.1 on 2024-01-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0003_alter_word_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='wordcategory',
            options={'verbose_name_plural': 'word categories'},
        ),
    ]
