# Generated by Django 5.0.1 on 2024-01-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0004_alter_category_options_alter_wordcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['name']},
        ),
    ]
